version: "3"
services:
  kofydash:
    container_name: kofydash
    build: .
    restart: always
    env_file:
      - .env.local
    networks:
      - app-network

  dashboard-nginx:
    container_name: dashboard-nginx
    image: jonasal/nginx-certbot
    restart: always
    environment:
      - CERTBOT_EMAIL=diego_gtz_t@hotmail.com
    ports:
      - 8080:80
      - 4043:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./user_conf.d:/etc/dashboard-nginx/user_conf.d
    depends_on:
      - kofydash
    networks:
      - app-network

volumes:
  nginx_secrets:

networks:
  app-network:
    driver: bridge